kind: pipeline
type: docker
name: default

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      repo: your-dockerhub-username/video-player-frontend
      tags: latest
      dockerfile: Dockerfile.frontend
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      port: 22
      key:
        from_secret: ssh_key
      script:
        - cd /opt/video-player-app
        - git fetch --all
        - git reset --hard origin/master
        - docker-compose -f docker-compose.prod.yml down
        - docker-compose -f docker-compose.prod.yml up -d
