spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/videoeeg
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  data:
    elasticsearch:
      cluster-nodes: localhost:9200
    mongodb:
      uri: mongodb://localhost:27017/video_player_db
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: video-bucket

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
